### ISSUE TITLE
WP-A Integration with PyShorteners and Quokka

### ISSUE THREAD

**Issue by vmesel** [vmesel/WP-A.CO#5]
Quokka is based in the PyShorteners lib, so @ellisonleao will implement it to be ready to go with the CMS and with the Lib!

https://github.com/ellisonleao/pyshorteners/issues/40

**Comment by ellisonleao** [comment]
Hey @vmesel i am trying to use the API, but i am getting 500 error on the response

tried:
`http://wp-a.co/api/?url=http://www.google.com&return=http`

any thoughts?

**Comment by vmesel** [comment]
You need to use the field customshort= too!
It can be left empty, but it is required!

I'm working on removing this field in the next update!

**Comment by ellisonleao** [comment]
same thing when adding that field 

tried

```
http://wp-a.co/api/?url=http://www.google.com&return=http&customshort=test
```

**Comment by vmesel** [comment]
The return doesnt exists, it is Method. So the url would be:

http://wp-a.co/api/?url=http://www.google.com&method=http&customshort=test
